### ISSUE TITLE
Dependency load order issue

### ISSUE THREAD

**Issue by laserlemon** [roguecomma/newrelic-faraday#4]
If you have `newrelic_rpm` and `newrelic-faraday` in your application's gemfile like so:

``` ruby
gem "newrelic-faraday"
gem "newrelic_rpm"
```

the following error is raised:

```
NameError: uninitialized constant DependencyDetection
/home/travis/build/collectiveidea/benefit-server/vendor/bundle/ruby/2.2.0/gems/newrelic-faraday-0.7.0/lib/newrelic_faraday/instrumentation.rb:1:in `<top (required)>'
/home/travis/build/collectiveidea/benefit-server/vendor/bundle/ruby/2.2.0/gems/newrelic-faraday-0.7.0/lib/newrelic-faraday.rb:1:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `require'
/home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `each'
/home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `block in require'
/home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `each'
/home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `require'
/home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler.rb:134:in `require'
```

I should mention that this error only seems to be raised in some environments. For instance, no error on my local machine but Travis explodes. The issue is that `newrelic-faraday` doesn't explicitly require its dependency on `newrelic_rpm`.

I believe that to fix this issue, the following should be added:

``` ruby
require "newrelic_rpm"

```

to the top of [lib/newrelic_faraday/instrumentation.rb](https://github.com/roguecomma/newrelic-faraday/blob/dd8f230/lib/newrelic_faraday/instrumentation.rb).

**Comment by kylev** [comment]
Fixed in 806553f.
